### ISSUE TITLE
item-selected and leaf-selected event handlers receive different parameters

### ISSUE THREAD

**Issue by rgov** [mynameistechno/finderjs#16]
The `leaf-selected` handler gets the JavaScript object from the tree data structure, while the `item-selected` handler gets an object containing the column div and item div that were clicked.

The documentation doesn't highlight the difference here.

I should be able to get information about the selected node that isn't a leaf; even in the first example with static data, the interior nodes still have metadata such as size and modification date.

**Comment by mynameistechno** [comment]
Thanks for the report @rgov. Makes sense. I don't have time to update this rn, but maybe over the next couple weeks. Feel free to submit a fix if you're interested though.

**Comment by rgov** [comment]
Ok, I sent you #17. I didn't attempt to fix the inconsistency between `item-selected` and `leaf-selected` because it would break backwards incompatibility, but I wrote an awkward note in the README about the situation.
