### ISSUE TITLE
Last column doesn't scroll into viewable window

### ISSUE THREAD

**Issue by arneysebaert** [mynameistechno/finderjs#19]
When selecting the last column visible on the current screen, the child-column is hidden and is only visible when scrolling. The window should auto-scroll to show that child-column in the current view.

**Comment by mynameistechno** [comment]
Hi @arneysebaert this is not built-in, but in the example it shows how to do this:

https://github.com/mynameistechno/finderjs/blob/master/example/example-async.js#L19

Let me know if this is not what you meant.
