### ISSUE TITLE
Cant load JSON

### ISSUE THREAD

**Issue by Bennith** [mynameistechno/finderjs#5]
I have duplicated the rest api json and ahve it as a file on my server. I have tested the json file is valid using json valid tool online, however when i use the file url as the uri for example-async but the spinner just keeps spinning. The rest API url works fine.

**Comment by mynameistechno** [comment]
Check the `console` for errors. Most browsers (e.g. Chrome) have a security policy by default that doesn't allow loading local files via XHR/Ajax. Chrome has an option you can pass in to it that overrides this, or you can start up a simple web server using Node express or something.

http://stackoverflow.com/questions/4819060/allow-google-chrome-to-use-xmlhttprequest-to-load-a-url-from-a-local-file
