### ISSUE TITLE
Method to navigate a specific path

### ISSUE THREAD

**Issue by devforfu** [mynameistechno/finderjs#8]
Is it possible to add a functionality that will allow to preset a specific path into FinderJS view? I mean, suppose we have the following "directory tree" (i.e. object):
```
+ root
     |
     + -- dir1
     + -- dir2
           |
           + -- file.txt
```

Then, we can do something like:
```javascript
var finder = createFinderJS();
finder.navigate('/dir2/file.txt');
```

And FinderJS will navigate to this path like if one do it manually using mouse or keyboard. Or, if it is not planned, could you please give a tip how to introduce this functionality manually?

**Comment by mynameistechno** [comment]
Sorry for the delay in response, did you ever sort something out? I'm low on free time, I'll try to take a look in the near future.

**Comment by devforfu** [comment]
Sure, no problem =) 

No, actually, I've decided to put it off for a some time. Or probably to try something like Dragula to write a custom control. 

Actually, the reason why I need this thing is an emulation of real file system behaviour where it is possible not only to navigate previously opened folder clicking "Back" button, but also to drag and drop folders/files from one subtree to another. Not sure if it's easy to introduce into FinderJS.

**Comment by doprdele** [comment]
I'm looking for a similar feature. I would like a path selected by default upon render. Is this possible?

**Comment by mynameistechno** [comment]
> I'm looking for a similar feature. I would like a path selected by default upon render. Is this possible?

No 😢 but I can see how that would be extremely useful. I might be able to take a look in a week or two, but feel free to take a look. 

This would be easier if written in React or something. As-is we probably need to add the item's value/label to the node's data-attribute to make it easier to find/navigate to it later. I'll think about it.

**Comment by mynameistechno** [comment]
This can now be done via a `defaultPath` config option (navigates on load):
```js
finder(container, data, {
  defaultPath: 'path/to/item'
});
```

or programmatically on demand:
```js
var emitter = finder(container, data);
emitter.emit('go-to', 'path/to/item');
```

**Comment by mynameistechno** [comment]
I added an example here:

https://markmatyas.dev/finderjs/
