### ISSUE TITLE
Pre-built files

### ISSUE THREAD

**Issue by clairetsai818** [mynameistechno/finderjs#9]
Hi! I am a member of CDNJS!
We would like to add this library to our CDN([issue](https://github.com/cdnjs/cdnjs/issues/10113)), could you please upload the pre-built files to GitHub repo or npm? Thanks!

**Comment by mynameistechno** [comment]
See https://github.com/cdnjs/cdnjs/issues/10113#issuecomment-297113704

Let me know if that doesn't work. Thanks.

**Comment by clairetsai818** [comment]
@mynameistechno Could you also upload the pre-built files to the repo or upload them to npm 'cause we can only fetch the files here through our auto-update. The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on git tags  so that it can recognize the correct version and automatically update the repo.
Could you please add git tags for the repo? Thanks!
